"""OEJP API package."""

from .auth import AuthenticatedGraphQLClient, AuthSession
from .client import DEFAULT_ENDPOINT, GraphQLResult, OejpGraphQLClient
from .device_auth import (
    DeviceAuthorization,
    DeviceAuthorizationDeniedError,
    DeviceAuthorizationError,
    DeviceAuthorizationExpiredError,
    DeviceAuthorizationPendingError,
    DeviceAuthorizationSlowDownError,
    DeviceAuthorizationTransientError,
    OejpDeviceAuthorizationClient,
)
from .errors import (
    GraphQLErrorDetail,
    OejpAuthenticationError,
    OejpAuthorizationError,
    OejpError,
    OejpGraphQLError,
    OejpInvalidResponseError,
    OejpNotFoundError,
    OejpQueryValidationError,
    OejpRateLimitError,
    OejpTimeoutError,
    OejpTransportError,
    classify_graphql_error_details,
    classify_graphql_errors,
)
from .models import (
    EnergyReading,
    EnergyUnit,
    OejpAccount,
    OejpSupplyPoint,
    ReadingDirection,
    ReadingQuality,
    ReadingSource,
)
from .operations import async_discover_accounts, async_get_viewer_identity

__all__ = [
    "DEFAULT_ENDPOINT",
    "AuthSession",
    "AuthenticatedGraphQLClient",
    "DeviceAuthorization",
    "DeviceAuthorizationDeniedError",
    "DeviceAuthorizationError",
    "DeviceAuthorizationExpiredError",
    "DeviceAuthorizationPendingError",
    "DeviceAuthorizationSlowDownError",
    "DeviceAuthorizationTransientError",
    "EnergyReading",
    "EnergyUnit",
    "GraphQLErrorDetail",
    "GraphQLResult",
    "OejpAccount",
    "OejpAuthenticationError",
    "OejpAuthorizationError",
    "OejpDeviceAuthorizationClient",
    "OejpError",
    "OejpGraphQLClient",
    "OejpGraphQLError",
    "OejpInvalidResponseError",
    "OejpNotFoundError",
    "OejpQueryValidationError",
    "OejpRateLimitError",
    "OejpSupplyPoint",
    "OejpTimeoutError",
    "OejpTransportError",
    "ReadingDirection",
    "ReadingQuality",
    "ReadingSource",
    "async_discover_accounts",
    "async_get_viewer_identity",
    "classify_graphql_error_details",
    "classify_graphql_errors",
]
