name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  python:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"
          cache: pip
      - run: python -m pip install --upgrade pip
      - run: pip install -e ".[test]"
      - run: ruff check custom_components tests
      - run: ruff format --check custom_components tests
      - run: mypy custom_components/octopus_energy_japan
      - run: pytest --cov --cov-report=term-missing --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: coverage.xml
          fail_ci_if_error: true
          use_oidc: true
          use_pypi: true

  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: home-assistant/actions/hassfest@e3fb68ebda13d88a0d695082f471ba2c83d025fb

  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: hacs/action@1ebf01c408f29afcb6406bd431bc98fd8cbb15aa
        with:
          category: integration

  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2
        with:
          args: >-
            --no-progress
            --exclude 'https://api\.oejp-kraken\.energy/v1/graphql/'
            --exclude 'https://docs\.oejp-kraken\.energy/graphql/changelog/'
            './**/*.md'
